options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_MEDIUM  # Tipo de máquina menos restritivo

steps:
  # Build e push da imagem n8n
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/n8n', './n8n']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/n8n']

# Deploy da imagem n8n no Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'n8n',
      '--image', 'gcr.io/$PROJECT_ID/n8n',
      '--region', 'us-east1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--timeout', '300s',  # Aumentar o timeout para 5 minutos
      '--set-env-vars', 'DB_TYPE=postgresdb,DB_POSTGRESDB_HOST=aws-0-us-west-1.pooler.supabase.com,DB_PORT=6543,DB_USER=postgres,DB_PASSWORD=smfluxo2025,DB_DATABASE=postgres,N8N_DIAGNOSTICS_ENABLED=false,N8N_PERSONALIZATION_ENABLED=false'
    ]


  # Build e push da imagem qdrant
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/qdrant', './qdrant']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/qdrant']

  # Deploy da imagem qdrant no Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'qdrant',
      '--image', 'gcr.io/$PROJECT_ID/qdrant',
      '--region', 'us-east1',  # Adicione a região aqui
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

  # Build e push da imagem ollama
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ollama', './ollama']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ollama']

  # Deploy da imagem ollama no Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'ollama',
      '--image', 'gcr.io/$PROJECT_ID/ollama',
      '--region', 'us-east1',  # Adicione a região aqui
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

images:
  - 'gcr.io/$PROJECT_ID/n8n'
  - 'gcr.io/$PROJECT_ID/qdrant'
  - 'gcr.io/$PROJECT_ID/ollama'
