steps:
  # Build e push da imagem n8n
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/n8n', './n8n']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/n8n']

  # Deploy da imagem n8n no Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'n8n',
      '--image', 'gcr.io/$PROJECT_ID/n8n',
      '--region', 'us-central1',  # Substitua pela sua região
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

  # Build e push da imagem qdrant
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/qdrant', './qdrant']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/qdrant']

  # Deploy da imagem qdrant no Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'qdrant',
      '--image', 'gcr.io/$PROJECT_ID/qdrant',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

  # Build e push da imagem ollama
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ollama', './ollama']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ollama']

  # Deploy da imagem ollama no Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'ollama',
      '--image', 'gcr.io/$PROJECT_ID/ollama',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

images:
  - 'gcr.io/$PROJECT_ID/n8n'
  - 'gcr.io/$PROJECT_ID/qdrant'
  - 'gcr.io/$PROJECT_ID/ollama'
