# Use a imagem Ollama
FROM ollama/ollama:latest

# Exponha a porta usada pelo Ollama
EXPOSE 11434

# Adicione o volume para o armazenamento do Ollama (configurado para o Cloud Storage no Cloud Run)
VOLUME /root/.ollama
